# Generated by Django 6.0.1 on 2026-01-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=100)),
                (
                    "documento_cliente",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("telefono_cliente", models.CharField(max_length=20)),
                ("direccion_cliente", models.CharField(max_length=150)),
                (
                    "email_cliente",
                    models.EmailField(blank=True, max_length=50, null=True),
                ),
                ("estado_activo_cliente", models.BooleanField(default=True)),
                ("fecha_creacion_cliente", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion_cliente", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacturaCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_factura_compra", models.DateTimeField(auto_now_add=True)),
                (
                    "total_factura_compra",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("actualizacion_factura_compra", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=50)),
                ("descripcion_producto", models.TextField(blank=True, null=True)),
                (
                    "precio_compra_producto",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "precio_venta_producto",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("stock_producto", models.IntegerField(default=0)),
                ("estado_activo_producto", models.BooleanField(default=True)),
                ("fecha_creacion_producto", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion_producto", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_proveedor", models.CharField(max_length=100)),
                (
                    "documento_proveedor",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("telefono_proveedor", models.CharField(max_length=20)),
                ("direccion_proveedor", models.CharField(max_length=150)),
                (
                    "email_proveedor",
                    models.EmailField(blank=True, max_length=50, null=True),
                ),
                ("estado_activo_proveedor", models.BooleanField(default=True)),
                ("fecha_creacion_proveedor", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion_proveedor", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacturaVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_factura_venta", models.DateTimeField(auto_now_add=True)),
                (
                    "total_factura_venta",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("actualizacion_factura_venta", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="facturas_venta",
                        to="core.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fecha_pago_compra", models.DateTimeField(auto_now_add=True)),
                ("actualizacion_pago_compra", models.DateTimeField(auto_now=True)),
                (
                    "factura_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pagos",
                        to="core.facturacompra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagoVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fecha_pago_venta", models.DateTimeField(auto_now_add=True)),
                ("actualizacion_pago_venta", models.DateTimeField(auto_now=True)),
                (
                    "factura_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pagos",
                        to="core.facturaventa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleFacturaVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_detalle_venta", models.IntegerField()),
                (
                    "precio_unitario_detalle_venta",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "subtotal_detalle_venta",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "fecha_creacion_detalle_venta",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "fecha_actualizacion_detalle_venta",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "factura_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.facturaventa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.producto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleFacturaCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_detalle_compra", models.IntegerField()),
                (
                    "precio_unitario_detalle_compra",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "subtotal_detalle_compra",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "fecha_creacion_detalle_compra",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "fecha_actualizacion_detalle_compra",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "factura_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="core.facturacompra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="core.producto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="facturacompra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="facturas_compra",
                to="core.proveedor",
            ),
        ),
    ]
